In [9]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.dpi'] = 70 #display 70 dpi in Jupyter Notebook, may consider100 dpi 
plt.rcParams['savefig.dpi'] = 300 #define 300 dpi for saving figures

import pandas as pd
import numpy as np

from sklearn.model_selection import KFold 
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneOut

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report

import seaborn as sns
## here are some settings 
sns.set_style('whitegrid')
sns.set(rc={"figure.dpi":70, 'savefig.dpi':300}) #defining dpi setting
sns.set_context('notebook')
sns.set_style("ticks")
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('retina')
# Tells matplotlib to display images inline instead of a new window
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from time import time
import timeit #imports timeit module
start_time = timeit.default_timer() #defines start time so computational time can be calculated
print("Hello World")
elapsed = timeit.default_timer() - start_time #gives total computation time
print("---Run time is %s seconds ---" % elapsed) #prints computation time
print()

Hello World
---Run time is 0.0002983999999912612 seconds ---



In [10]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.preprocessing import PolynomialFeatures

import sklearn.linear_model as skl_lm
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn import neighbors
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeRegressor 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.tree import export_graphviz
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [11]:
df2017 = pd.read_csv('SRER_2017_training_bi.csv').dropna()
df2017 = df2017.drop(df2017.columns[[0, 1, 2, 3, 4]], axis=1)
df2017.head(5)

CH_mean  ARVI_max  ARVI_mean  ARVI_med   EVI_max  EVI_mean   EVI_med  \
0  0.190714  0.609099   0.344183  0.379428  0.443455  0.292047  0.290985   
1  0.045000  0.387755   0.245301  0.274936  0.332059  0.252919  0.244477   
2  0.010000  0.038844   0.004040  0.026805  0.150550  0.131985  0.134891   
3  0.011667  0.189842   0.033418  0.018961  0.198972  0.141579  0.138338   
4  0.013750  0.322694   0.080315  0.061453  0.248442  0.158710  0.142326   

   NDVI_max  NDVI_mean  NDVI_med  SAVI_max  SAVI_mean  SAVI_med  Veg_class  
0  0.665698   0.476709  0.507514  0.406991   0.286203  0.288351      woody  
1  0.526375   0.406745  0.433791  0.328585   0.254814  0.248126  non-woody  
2  0.208300   0.181575  0.205117  0.150184   0.131642  0.135063  non-woody  
3  0.341480   0.207390  0.197327  0.197330   0.141500  0.138725  non-woody  
4  0.457103   0.247391  0.228112  0.248598   0.158618  0.142817  non-woody

In [12]:
df2017.Veg_class = df2017.Veg_class.map({'non-woody':0, 'woody':1})

df2017.head(5)

CH_mean  ARVI_max  ARVI_mean  ARVI_med   EVI_max  EVI_mean   EVI_med  \
0  0.190714  0.609099   0.344183  0.379428  0.443455  0.292047  0.290985   
1  0.045000  0.387755   0.245301  0.274936  0.332059  0.252919  0.244477   
2  0.010000  0.038844   0.004040  0.026805  0.150550  0.131985  0.134891   
3  0.011667  0.189842   0.033418  0.018961  0.198972  0.141579  0.138338   
4  0.013750  0.322694   0.080315  0.061453  0.248442  0.158710  0.142326   

   NDVI_max  NDVI_mean  NDVI_med  SAVI_max  SAVI_mean  SAVI_med  Veg_class  
0  0.665698   0.476709  0.507514  0.406991   0.286203  0.288351          1  
1  0.526375   0.406745  0.433791  0.328585   0.254814  0.248126          0  
2  0.208300   0.181575  0.205117  0.150184   0.131642  0.135063          0  
3  0.341480   0.207390  0.197327  0.197330   0.141500  0.138725          0  
4  0.457103   0.247391  0.228112  0.248598   0.158618  0.142817          0

In [13]:
X = df2017.drop(['Veg_class'], axis = 1)
y = df2017.Veg_class
print(X.shape)
print(y.shape)

(4339, 13)
(4339,)


In [14]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6) #criterion='entropy'
scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))


Accuracy of each fold: 
 [0.66820276 0.68548387 0.6624424  0.69009217 0.67243368]

Avg accuracy: 0.6757309755021553


In [17]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

Accuracy of each fold: 
 [0.66820276 0.66129032 0.66589862 0.70276498 0.66782007]

Avg accuracy: 0.6731953502463603


In [18]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 3, random_state = 2)
scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

Accuracy of each fold: 
 [0.68087558 0.68778802 0.67511521 0.69930876 0.66551326]

Avg accuracy: 0.6817201643465736


In [19]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

Accuracy of each fold: 
 [0.68087558 0.69585253 0.68087558 0.69585253 0.68973472]

Avg accuracy: 0.688638187722907


In [20]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
scores = cross_val_score(model, X, y, cv=crossvalidation)
print('Accuracy of each fold: \n {}'.format(scores))
print()
print("Avg accuracy: {}".format(scores.mean()))

Accuracy of each fold: 
 [0.65437788 0.67511521 0.67165899 0.6843318  0.66205306]

Avg accuracy: 0.6695073854968933
