In [2]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.dpi'] = 70 #display 70 dpi in Jupyter Notebook, may consider100 dpi 
plt.rcParams['savefig.dpi'] = 300 #define 300 dpi for saving figures

import seaborn as sns
## here are some settings 
sns.set_style('whitegrid')
sns.set(rc={"figure.dpi":70, 'savefig.dpi':300}) #defining dpi setting
sns.set_context('notebook')
sns.set_style("ticks")
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('retina')
# Tells matplotlib to display images inline instead of a new window
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
random.seed(1000)

from time import time
import timeit #imports timeit module
start_time = timeit.default_timer() #defines start time so computational time can be calculated
print("Hello World")
elapsed = timeit.default_timer() - start_time #gives total computation time
print("---Run time is %s seconds ---" % elapsed) #prints computation time
print()

Hello World
---Run time is 0.0003375999999946089 seconds ---



In [3]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.preprocessing import PolynomialFeatures

import sklearn.linear_model as skl_lm
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn import neighbors
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeRegressor 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.tree import export_graphviz
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [4]:
df2017 = pd.read_csv('SRER_2017_training_bi.csv', na_values = '?').dropna()
df2021 = pd.read_csv("SRER21_dataset_v1.csv", na_values = '?').dropna()
dfJornada2017 = pd.read_csv("JORN17_dataset_v1.csv", na_values = '?').dropna()
dfJornada2021 = pd.read_csv("JORN21_dataset_v1.csv", na_values = '?').dropna()
dfJornada2017["Year"] = '2017'
dfJornada2021["Year"] = '2021'

frames = [dfJornada2017,dfJornada2021]

dfCombined = pd.concat(frames)
dfCombined = dfCombined.reindex(columns=['OID_','Id', 'gridcode','Shape_Length','Shape_Area', 'CH_mean', 'ARVI_max', 'ARVI_mean', 'ARVI_med', 'EVI_max', 'EVI_mean', 'EVI_med', 'NDVI_max', 'NDVI_mean', 'NDVI_med', 'SAVI_max', 'SAVI_mean', 'SAVI_med', 'Year', 'Veg_class'])

dfCombined

OID_    Id  gridcode  Shape_Length  Shape_Area   CH_mean  ARVI_max  \
0        2     2         2          16.0        4.79  0.010000  0.239161   
1        3     3         3           8.6        2.24  0.010000  0.316384   
2        4     4         4          27.8       11.12  0.012500  0.459671   
3        5     5         5          24.2       10.62  0.060000  0.498250   
4        6     6         6          17.4        6.10  0.012000  0.416294   
...    ...   ...       ...           ...         ...       ...       ...   
2226  2278  2278      2278          25.2        6.63  0.015000  0.167685   
2227  2279  2279      2279          15.2        5.33  0.134000  0.519026   
2228  2280  2280      2280          17.0        4.98  0.114000  0.474006   
2229  2281  2281      2281          19.8        6.49  0.011667  0.198284   
2230  2282  2282      2282          14.8        4.36  0.018000  0.415063   

      ARVI_mean  ARVI_med   EVI_max  EVI_mean   EVI_med  NDVI_max  NDVI_mean  \
0      0.223962  0.226896  0.307885  0.273236  0.274394  0.427636   0.402131   
1      0.287822  0.287822  0.305906  0.302193  0.302193  0.469259   0.448325   
2      0.289236  0.313074  0.374641  0.300200  0.318621  0.570786   0.447470   
3      0.330255  0.375986  0.386369  0.313174  0.335601  0.598966   0.477596   
4      0.275800  0.341526  0.314841  0.264112  0.280268  0.518614   0.431575   
...         ...       ...       ...       ...       ...       ...        ...   
2226   0.128259  0.134121  0.256763  0.237659  0.245145  0.365527   0.334798   
2227   0.485618  0.489819  0.441772  0.416102  0.438885  0.603520   0.583201   
2228   0.313633  0.318283  0.436805  0.350407  0.341923  0.591361   0.483337   
2229   0.119920  0.108993  0.271254  0.230958  0.227932  0.384514   0.323523   
2230   0.358501  0.379463  0.365760  0.324313  0.338486  0.529712   0.493172   

      NDVI_med  SAVI_max  SAVI_mean  SAVI_med  Year  Veg_class  
0     0.406066  0.316995   0.278782  0.280285  2017      woody  
1     0.448325  0.304224   0.301407  0.301407  2017      woody  
2     0.466219  0.358302   0.298798  0.314429  2017      woody  
3     0.517136  0.368766   0.309534  0.325886  2017      woody  
4     0.487791  0.312146   0.266352  0.273629  2017      woody  
...        ...       ...        ...       ...   ...        ...  
2226  0.337580  0.268680   0.252164  0.257355  2021  non-woody  
2227  0.585438  0.410255   0.386171  0.403764  2021      woody  
2228  0.490012  0.412744   0.350956  0.346441  2021  non-woody  
2229  0.317326  0.278123   0.243325  0.242532  2021  non-woody  
2230  0.516169  0.349468   0.315355  0.326305  2021      woody  

[4790 rows x 20 columns]

In [5]:
df2017.Veg_class = df2017.Veg_class.map({'non-woody':0, 'woody':1})
df2021.Veg_class = df2021.Veg_class.map({'non-woody':0, 'woody':1})
dfJornada2017.Veg_class = dfJornada2017.Veg_class.map({'non-woody':0, 'woody':1})
dfJornada2021.Veg_class = dfJornada2021.Veg_class.map({'non-woody':0, 'woody':1})
dfCombined.Veg_class = dfCombined.Veg_class.map({'non-woody':0, 'woody':1})

In [13]:
dfJornada2017.shape

(2649, 19)

In [14]:
#2017 Jorn (Training) to 2021 Jorn (Testing)

In [23]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = dfJornada2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 1007.5522134999999 seconds ---

Accuracy of each fold: 
 [0.7016317016317016, 0.7266355140186916, 0.6892523364485982, 0.6845794392523364, 0.7009345794392523]
Avg accuracy: 0.700606714158116
Std of accuracy : 
0.014590763867743942

[[ 158  540]
 [ 101 1342]]

              precision    recall  f1-score   support

           0       0.61      0.23      0.33       698
           1       0.71      0.93      0.81      1443

    accuracy                           0.70      2141
   macro avg       0.66      0.58      0.57      2141
weighted avg       0.68      0.70      0.65      2141

Sensitivity: 0.22636103151862463
Specificity: 0.93000693000693
Precision: 0.61003861003861
F1_Score: 0.33019853709508884


In [21]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = dfJornada2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 830.5387425 seconds ---

Accuracy of each fold: 
 [0.7505827505827506, 0.7079439252336449, 0.7406542056074766, 0.7219626168224299, 0.7406542056074766]
Avg accuracy: 0.7323595407707557
Std of accuracy : 
0.015322575599437144

[[ 182  516]
 [  57 1386]]

              precision    recall  f1-score   support

           0       0.76      0.26      0.39       698
           1       0.73      0.96      0.83      1443

    accuracy                           0.73      2141
   macro avg       0.75      0.61      0.61      2141
weighted avg       0.74      0.73      0.69      2141

Sensitivity: 0.2607449856733524
Specificity: 0.9604989604989606
Precision: 0.7615062761506276
F1_Score: 0.38847385272145135


In [19]:
#Ada boost

crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = dfJornada2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 617.0945138 seconds ---

Accuracy of each fold: 
 [0.7435897435897436, 0.6752336448598131, 0.7219626168224299, 0.719626168224299, 0.6892523364485982]
Avg accuracy: 0.7099329019889768
Std of accuracy : 
0.024507879027805986

[[  90  608]
 [  13 1430]]

              precision    recall  f1-score   support

           0       0.87      0.13      0.22       698
           1       0.70      0.99      0.82      1443

    accuracy                           0.71      2141
   macro avg       0.79      0.56      0.52      2141
weighted avg       0.76      0.71      0.63      2141

Sensitivity: 0.12893982808022922
Specificity: 0.990990990990991
Precision: 0.8737864077669902
F1_Score: 0.22471910112359547


In [16]:
#Gradient Boosting


crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = dfJornada2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 397.25527950000003 seconds ---

Accuracy of each fold: 
 [0.7435897435897436, 0.7102803738317757, 0.7429906542056075, 0.7149532710280374, 0.7383177570093458]
Avg accuracy: 0.730026359932902
Std of accuracy : 
0.014407550408942316

[[ 192  506]
 [  72 1371]]

              precision    recall  f1-score   support

           0       0.73      0.28      0.40       698
           1       0.73      0.95      0.83      1443

    accuracy                           0.73      2141
   macro avg       0.73      0.61      0.61      2141
weighted avg       0.73      0.73      0.69      2141

Sensitivity: 0.27507163323782235
Specificity: 0.9501039501039501
Precision: 0.7272727272727273
F1_Score: 0.39916839916839914


In [24]:
#2021 Jorn (Training) to 2017 Jorn (Testing)

In [30]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2021.iloc[train_index, 5:18]
    X_test = dfJornada2017.iloc[test_index, 5:18]
    Y_train = dfJornada2021.iloc[train_index, -1]
    Y_test = dfJornada2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 1852.6496797 seconds ---

Accuracy of each fold: 
 [0.6503496503496503, 0.7313084112149533, 0.7126168224299065, 0.7219626168224299, 0.6612149532710281]
Avg accuracy: 0.6954904908175936
Std of accuracy : 
0.03313462256782401

[[ 322  141]
 [ 511 1167]]

              precision    recall  f1-score   support

           0       0.39      0.70      0.50       463
           1       0.89      0.70      0.78      1678

    accuracy                           0.70      2141
   macro avg       0.64      0.70      0.64      2141
weighted avg       0.78      0.70      0.72      2141

Sensitivity: 0.6954643628509719
Specificity: 0.6954707985697258
Precision: 0.3865546218487395
F1_Score: 0.4969135802469136


In [29]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2021.iloc[train_index, 5:18]
    X_test = dfJornada2017.iloc[test_index, 5:18]
    Y_train = dfJornada2021.iloc[train_index, -1]
    Y_test = dfJornada2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1502.5698974 seconds ---

Accuracy of each fold: 
 [0.668997668997669, 0.7009345794392523, 0.7242990654205608, 0.7266355140186916, 0.7126168224299065]
Avg accuracy: 0.706696730061216
Std of accuracy : 
0.02096123276108921

[[ 317  146]
 [ 482 1196]]

              precision    recall  f1-score   support

           0       0.40      0.68      0.50       463
           1       0.89      0.71      0.79      1678

    accuracy                           0.71      2141
   macro avg       0.64      0.70      0.65      2141
weighted avg       0.78      0.71      0.73      2141

Sensitivity: 0.6846652267818575
Specificity: 0.7127532777115614
Precision: 0.3967459324155194
F1_Score: 0.502377179080824


In [28]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2021.iloc[train_index, 5:18]
    X_test = dfJornada2017.iloc[test_index, 5:18]
    Y_train = dfJornada2021.iloc[train_index, -1]
    Y_test = dfJornada2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1412.8882977 seconds ---

Accuracy of each fold: 
 [0.6643356643356644, 0.6682242990654206, 0.7219626168224299, 0.7313084112149533, 0.6939252336448598]
Avg accuracy: 0.6959512450166656
Std of accuracy : 
0.02719983036877213

[[ 310  153]
 [ 498 1180]]

              precision    recall  f1-score   support

           0       0.38      0.67      0.49       463
           1       0.89      0.70      0.78      1678

    accuracy                           0.70      2141
   macro avg       0.63      0.69      0.64      2141
weighted avg       0.78      0.70      0.72      2141

Sensitivity: 0.6695464362850972
Specificity: 0.7032181168057211
Precision: 0.38366336633663367
F1_Score: 0.48780487804878053


In [26]:
#Gradient Boosting


crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = dfJornada2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = dfJornada2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1272.9465154 seconds ---

Accuracy of each fold: 
 [0.7435897435897436, 0.7102803738317757, 0.7429906542056075, 0.7149532710280374, 0.7383177570093458]
Avg accuracy: 0.730026359932902
Std of accuracy : 
0.014407550408942316

[[ 192  506]
 [  72 1371]]

              precision    recall  f1-score   support

           0       0.73      0.28      0.40       698
           1       0.73      0.95      0.83      1443

    accuracy                           0.73      2141
   macro avg       0.73      0.61      0.61      2141
weighted avg       0.73      0.73      0.69      2141

Sensitivity: 0.27507163323782235
Specificity: 0.9501039501039501
Precision: 0.7272727272727273
F1_Score: 0.39916839916839914


In [35]:
#2017 SRER (Training) to 2021 Jorn (Testing)


In [51]:
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = DecisionTreeClassifier(max_depth=6) #criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 3984.7700815000003 seconds ---

Accuracy of each fold: 
 [0.7202797202797203, 0.7289719626168224, 0.7827102803738317, 0.705607476635514, 0.6448598130841121]
Avg accuracy: 0.7164858505980002
Std of accuracy : 
0.04428227593439862

[[ 353  345]
 [ 262 1181]]

              precision    recall  f1-score   support

           0       0.57      0.51      0.54       698
           1       0.77      0.82      0.80      1443

    accuracy                           0.72      2141
   macro avg       0.67      0.66      0.67      2141
weighted avg       0.71      0.72      0.71      2141

Sensitivity: 0.505730659025788
Specificity: 0.8184338184338185
Precision: 0.5739837398373984
F1_Score: 0.5376999238385377


In [52]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 4012.5537627000003 seconds ---

Accuracy of each fold: 
 [0.662004662004662, 0.6425233644859814, 0.6892523364485982, 0.6565420560747663, 0.633177570093458]
Avg accuracy: 0.6566999978214931
Std of accuracy : 
0.019194273608216853

[[ 404  294]
 [ 441 1002]]

              precision    recall  f1-score   support

           0       0.48      0.58      0.52       698
           1       0.77      0.69      0.73      1443

    accuracy                           0.66      2141
   macro avg       0.63      0.64      0.63      2141
weighted avg       0.68      0.66      0.66      2141

Sensitivity: 0.5787965616045845
Specificity: 0.6943866943866944
Precision: 0.47810650887573963
F1_Score: 0.5236552171095268


In [53]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 4048.4801246 seconds ---

Accuracy of each fold: 
 [0.6899766899766899, 0.6985981308411215, 0.6915887850467289, 0.647196261682243, 0.6495327102803738]
Avg accuracy: 0.6753785155654315
Std of accuracy : 
0.02225881915609393

[[ 132  566]
 [ 129 1314]]

              precision    recall  f1-score   support

           0       0.51      0.19      0.28       698
           1       0.70      0.91      0.79      1443

    accuracy                           0.68      2141
   macro avg       0.60      0.55      0.53      2141
weighted avg       0.64      0.68      0.62      2141

Sensitivity: 0.18911174785100288
Specificity: 0.9106029106029107
Precision: 0.5057471264367817
F1_Score: 0.27528675703858185


In [54]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 4102.1882469 seconds ---

Accuracy of each fold: 
 [0.627039627039627, 0.633177570093458, 0.6098130841121495, 0.6588785046728972, 0.6682242990654206]
Avg accuracy: 0.6394266169967106
Std of accuracy : 
0.02134072099999624

[[472 226]
 [546 897]]

              precision    recall  f1-score   support

           0       0.46      0.68      0.55       698
           1       0.80      0.62      0.70      1443

    accuracy                           0.64      2141
   macro avg       0.63      0.65      0.62      2141
weighted avg       0.69      0.64      0.65      2141

Sensitivity: 0.6762177650429799
Specificity: 0.6216216216216216
Precision: 0.4636542239685658
F1_Score: 0.55011655011655


In [ ]:
#2021 SRER (Training) to 2021 Jorn (Testing)

In [56]:
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = DecisionTreeClassifier(max_depth=6) #criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 5150.1953007 seconds ---

Accuracy of each fold: 
 [0.4382284382284382, 0.5630841121495327, 0.5537383177570093, 0.5093457943925234, 0.5280373831775701]
Avg accuracy: 0.5184868091410147
Std of accuracy : 
0.04437964851581787

[[635  63]
 [968 475]]

              precision    recall  f1-score   support

           0       0.40      0.91      0.55       698
           1       0.88      0.33      0.48      1443

    accuracy                           0.52      2141
   macro avg       0.64      0.62      0.52      2141
weighted avg       0.72      0.52      0.50      2141

Sensitivity: 0.9097421203438395
Specificity: 0.32917532917532916
Precision: 0.39613225202744856
F1_Score: 0.5519339417644503


In [57]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 5158.297985900001 seconds ---

Accuracy of each fold: 
 [0.5431235431235432, 0.5210280373831776, 0.544392523364486, 0.544392523364486, 0.5163551401869159]
Avg accuracy: 0.5338583534845217
Std of accuracy : 
0.012480069680645366

[[520 178]
 [820 623]]

              precision    recall  f1-score   support

           0       0.39      0.74      0.51       698
           1       0.78      0.43      0.56      1443

    accuracy                           0.53      2141
   macro avg       0.58      0.59      0.53      2141
weighted avg       0.65      0.53      0.54      2141

Sensitivity: 0.7449856733524355
Specificity: 0.43173943173943174
Precision: 0.3880597014925373
F1_Score: 0.5103042198233562


In [58]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 5177.1753029 seconds ---

Accuracy of each fold: 
 [0.5361305361305362, 0.5584112149532711, 0.5233644859813084, 0.5093457943925234, 0.5397196261682243]
Avg accuracy: 0.5333943315251727
Std of accuracy : 
0.016445489133942365

[[670  28]
 [971 472]]

              precision    recall  f1-score   support

           0       0.41      0.96      0.57       698
           1       0.94      0.33      0.49      1443

    accuracy                           0.53      2141
   macro avg       0.68      0.64      0.53      2141
weighted avg       0.77      0.53      0.51      2141

Sensitivity: 0.9598853868194842
Specificity: 0.3270963270963271
Precision: 0.4082876294942108
F1_Score: 0.572894399315947


In [59]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2021): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = dfJornada2021.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = dfJornada2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 5226.7170587 seconds ---

Accuracy of each fold: 
 [0.5081585081585082, 0.5, 0.5116822429906542, 0.5186915887850467, 0.4976635514018692]
Avg accuracy: 0.5072391782672157
Std of accuracy : 
0.007692100234701685

[[540 158]
 [897 546]]

              precision    recall  f1-score   support

           0       0.38      0.77      0.51       698
           1       0.78      0.38      0.51      1443

    accuracy                           0.51      2141
   macro avg       0.58      0.58      0.51      2141
weighted avg       0.65      0.51      0.51      2141

Sensitivity: 0.7736389684813754
Specificity: 0.3783783783783784
Precision: 0.3757828810020877
F1_Score: 0.5058548009367682


In [37]:
#2017 SRER TO 2017 JORN

In [46]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2017.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 3416.8259887000004 seconds ---

Accuracy of each fold: 
 [0.4377358490566038, 0.7396226415094339, 0.690566037735849, 0.6320754716981132, 0.6937618147448015]
Avg accuracy: 0.6387523629489603
Std of accuracy : 
0.10614869713084527

[[ 312  365]
 [ 592 1380]]

              precision    recall  f1-score   support

           0       0.35      0.46      0.39       677
           1       0.79      0.70      0.74      1972

    accuracy                           0.64      2649
   macro avg       0.57      0.58      0.57      2649
weighted avg       0.68      0.64      0.65      2649

Sensitivity: 0.4608567208271787
Specificity: 0.6997971602434077
Precision: 0.34513274336283184
F1_Score: 0.3946869070208729


In [49]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_depth=6)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2017.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 3525.7383508000003 seconds ---

Accuracy of each fold: 
 [0.6547169811320754, 0.7, 0.6811320754716981, 0.720754716981132, 0.720226843100189]
Avg accuracy: 0.695366123337019
Std of accuracy : 
0.02505621586723127

[[ 419  258]
 [ 549 1423]]

              precision    recall  f1-score   support

           0       0.43      0.62      0.51       677
           1       0.85      0.72      0.78      1972

    accuracy                           0.70      2649
   macro avg       0.64      0.67      0.64      2649
weighted avg       0.74      0.70      0.71      2649

Sensitivity: 0.6189069423929099
Specificity: 0.7216024340770791
Precision: 0.43285123966942146
F1_Score: 0.5094224924012157


In [48]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2017.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 3520.0201810000003 seconds ---

Accuracy of each fold: 
 [0.6773584905660377, 0.7169811320754716, 0.7018867924528301, 0.7037735849056603, 0.7391304347826086]
Avg accuracy: 0.7078260869565216
Std of accuracy : 
0.020217563977066547

[[ 126  551]
 [ 223 1749]]

              precision    recall  f1-score   support

           0       0.36      0.19      0.25       677
           1       0.76      0.89      0.82      1972

    accuracy                           0.71      2649
   macro avg       0.56      0.54      0.53      2649
weighted avg       0.66      0.71      0.67      2649

Sensitivity: 0.1861152141802068
Specificity: 0.8869168356997972
Precision: 0.36103151862464183
F1_Score: 0.2456140350877193


In [47]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = dfJornada2017.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = dfJornada2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 3485.9874314000003 seconds ---

Accuracy of each fold: 
 [0.4377358490566038, 0.44528301886792454, 0.39622641509433965, 0.439622641509434, 0.40831758034026466]
Avg accuracy: 0.4254371009737133
Std of accuracy : 
0.019456060125437852

[[ 521  156]
 [1366  606]]

              precision    recall  f1-score   support

           0       0.28      0.77      0.41       677
           1       0.80      0.31      0.44      1972

    accuracy                           0.43      2649
   macro avg       0.54      0.54      0.42      2649
weighted avg       0.66      0.43      0.43      2649

Sensitivity: 0.7695716395864106
Specificity: 0.30730223123732253
Precision: 0.27609962904080554
F1_Score: 0.4063962558502341


In [1]:
#Combined


In [12]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:19]
    X_test = dfCombined.iloc[test_index, 5:19]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 212.57865160000006 seconds ---

Accuracy of each fold: 
 [0.7860125260960334, 0.7640918580375783, 0.7954070981210856, 0.7860125260960334, 0.7682672233820459]
Avg accuracy: 0.7799582463465553
Std of accuracy : 
0.011835522157042486

[[ 735  640]
 [ 414 3001]]

              precision    recall  f1-score   support

   non-woody       0.64      0.53      0.58      1375
       woody       0.82      0.88      0.85      3415

    accuracy                           0.78      4790
   macro avg       0.73      0.71      0.72      4790
weighted avg       0.77      0.78      0.77      4790

Sensitivity: 0.5345454545454545
Specificity: 0.8787701317715959
Precision: 0.639686684073107
F1_Score: 0.5824088748019018


In [14]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:19]
    X_test = dfCombined.iloc[test_index, 5:19]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 1233.5199241 seconds ---

Accuracy of each fold: 
 [0.8037578288100209, 0.791231732776618, 0.7901878914405011, 0.778705636743215, 0.7755741127348643]
Avg accuracy: 0.7878914405010439
Std of accuracy : 
0.010042599975620623

[[ 739  636]
 [ 380 3035]]

              precision    recall  f1-score   support

   non-woody       0.66      0.54      0.59      1375
       woody       0.83      0.89      0.86      3415

    accuracy                           0.79      4790
   macro avg       0.74      0.71      0.72      4790
weighted avg       0.78      0.79      0.78      4790

Sensitivity: 0.5374545454545454
Specificity: 0.8887262079062958
Precision: 0.6604110813226095
F1_Score: 0.5926222935044106


In [13]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_depth=6)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:19]
    X_test = dfCombined.iloc[test_index, 5:19]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 1120.7830826999998 seconds ---

Accuracy of each fold: 
 [0.7964509394572025, 0.8037578288100209, 0.8131524008350731, 0.7797494780793319, 0.7818371607515657]
Avg accuracy: 0.7949895615866389
Std of accuracy : 
0.01276050671393416

[[ 707  668]
 [ 314 3101]]

              precision    recall  f1-score   support

   non-woody       0.69      0.51      0.59      1375
       woody       0.82      0.91      0.86      3415

    accuracy                           0.79      4790
   macro avg       0.76      0.71      0.73      4790
weighted avg       0.79      0.79      0.78      4790

Sensitivity: 0.5141818181818182
Specificity: 0.9080527086383602
Precision: 0.692458374142997
F1_Score: 0.5901502504173622


In [15]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:19]
    X_test = dfCombined.iloc[test_index, 5:19]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 1479.9852984 seconds ---

Accuracy of each fold: 
 [0.802713987473904, 0.791231732776618, 0.7964509394572025, 0.7933194154488518, 0.7901878914405011]
Avg accuracy: 0.7947807933194154
Std of accuracy : 
0.004506687504159273

[[ 774  601]
 [ 382 3033]]

              precision    recall  f1-score   support

   non-woody       0.67      0.56      0.61      1375
       woody       0.83      0.89      0.86      3415

    accuracy                           0.79      4790
   macro avg       0.75      0.73      0.74      4790
weighted avg       0.79      0.79      0.79      4790

Sensitivity: 0.5629090909090909
Specificity: 0.8881405563689605
Precision: 0.6695501730103807
F1_Score: 0.611615962070328


In [6]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6)

#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

---Run time is 12.276497200000023 seconds ---

Accuracy of each fold: 
 [0.6889400921658986, 0.7108294930875576, 0.6785714285714286, 0.7131336405529954, 0.7231833910034602]
Avg accuracy: 0.7029316090762681
Std of accuracy : 
0.016527393194427125

[[ 312 1147]
 [ 142 2738]]

              precision    recall  f1-score   support

           0       0.69      0.21      0.33      1459
           1       0.70      0.95      0.81      2880

    accuracy                           0.70      4339
   macro avg       0.70      0.58      0.57      4339
weighted avg       0.70      0.70      0.65      4339

0.21384509938313914
0.9506944444444444
0.6872246696035242
0.3261892315734448


In [7]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)

#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

---Run time is 101.29513110000002 seconds ---

Accuracy of each fold: 
 [0.7684331797235023, 0.7695852534562212, 0.7707373271889401, 0.7557603686635944, 0.7681660899653979]
Avg accuracy: 0.7665364437995311
Std of accuracy : 
0.005464792964069163

[[ 720  739]
 [ 274 2606]]

              precision    recall  f1-score   support

           0       0.72      0.49      0.59      1459
           1       0.78      0.90      0.84      2880

    accuracy                           0.77      4339
   macro avg       0.75      0.70      0.71      4339
weighted avg       0.76      0.77      0.75      4339

0.49348869088416725
0.9048611111111111
0.7243460764587525
0.5870362821035466


In [8]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 3, random_state = 2)

#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

---Run time is 141.37268930000002 seconds ---

Accuracy of each fold: 
 [0.783410138248848, 0.7695852534562212, 0.7730414746543779, 0.738479262672811, 0.7358708189158016]
Avg accuracy: 0.7600773895896119
Std of accuracy : 
0.019263028250864164

[[ 658  801]
 [ 240 2640]]

              precision    recall  f1-score   support

           0       0.73      0.45      0.56      1459
           1       0.77      0.92      0.84      2880

    accuracy                           0.76      4339
   macro avg       0.75      0.68      0.70      4339
weighted avg       0.76      0.76      0.74      4339

0.45099383139136395
0.9166666666666666
0.732739420935412
0.5583368689011454


In [9]:
#Bagging Code

In [10]:
#Bagging 2017 -> 2021 SRER 

In [11]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 803.2861290000001 seconds ---

Accuracy of each fold: 
 [0.7684331797235023, 0.7695852534562212, 0.7707373271889401, 0.7557603686635944, 0.7681660899653979]
Avg accuracy: 0.7665364437995311
Std of accuracy : 
0.005464792964069163

[[ 720  739]
 [ 274 2606]]

              precision    recall  f1-score   support

           0       0.72      0.49      0.59      1459
           1       0.78      0.90      0.84      2880

    accuracy                           0.77      4339
   macro avg       0.75      0.70      0.71      4339
weighted avg       0.76      0.77      0.75      4339

0.49348869088416725
0.9048611111111111
0.7243460764587525
0.5870362821035466


In [12]:
#Random Forest 2017 -> 2021 SRER 

In [13]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 3, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 874.8300282 seconds ---

Accuracy of each fold: 
 [0.783410138248848, 0.7695852534562212, 0.7730414746543779, 0.738479262672811, 0.7358708189158016]
Avg accuracy: 0.7600773895896119
Std of accuracy : 
0.019263028250864164

[[ 658  801]
 [ 240 2640]]

              precision    recall  f1-score   support

           0       0.73      0.45      0.56      1459
           1       0.77      0.92      0.84      2880

    accuracy                           0.76      4339
   macro avg       0.75      0.68      0.70      4339
weighted avg       0.76      0.76      0.74      4339

0.45099383139136395
0.9166666666666666
0.732739420935412
0.5583368689011454


In [14]:
#Bagging 2021 -> 2017 SRER 

In [15]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(df2017): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1032.5774026 seconds ---

Accuracy of each fold: 
 [0.4619815668202765, 0.4804147465437788, 0.5023041474654378, 0.4066820276497696, 0.44521337946943484]
Avg accuracy: 0.45931917358973956
Std of accuracy : 
0.0324637092013152

[[ 413 1675]
 [ 671 1580]]

              precision    recall  f1-score   support

           0       0.38      0.20      0.26      2088
           1       0.49      0.70      0.57      2251

    accuracy                           0.46      4339
   macro avg       0.43      0.45      0.42      4339
weighted avg       0.44      0.46      0.42      4339

0.1977969348659004
0.7019102621057308
0.38099630996309963
0.2604035308953342


In [18]:
# Random Forest 2021 -> 2017

In [17]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 3, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(df2017): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1068.7303933 seconds ---

Accuracy of each fold: 
 [0.4827188940092166, 0.5357142857142857, 0.5506912442396313, 0.49193548387096775, 0.4867358708189158]
Avg accuracy: 0.5095591557306035
Std of accuracy : 
0.028027969326465837

[[ 474 1614]
 [ 514 1737]]

              precision    recall  f1-score   support

           0       0.48      0.23      0.31      2088
           1       0.52      0.77      0.62      2251

    accuracy                           0.51      4339
   macro avg       0.50      0.50      0.46      4339
weighted avg       0.50      0.51      0.47      4339

0.22701149425287356
0.7716570413149711
0.4797570850202429
0.3081924577373212


In [19]:
#Bagging Combined SRER 

In [20]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in crossvalidation.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:18]
    X_test = dfCombined.iloc[test_index, 5:18]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1221.5127601 seconds ---

Accuracy of each fold: 
 [0.7546972860125261, 0.7985386221294363, 0.7933194154488518, 0.7860125260960334, 0.7807933194154488]
Avg accuracy: 0.7826722338204593
Std of accuracy : 
0.015247231429236091

[[ 764  611]
 [ 430 2985]]

              precision    recall  f1-score   support

           0       0.64      0.56      0.59      1375
           1       0.83      0.87      0.85      3415

    accuracy                           0.78      4790
   macro avg       0.73      0.71      0.72      4790
weighted avg       0.78      0.78      0.78      4790

0.5556363636363636
0.8740849194729137
0.6398659966499163
0.5947839626313741
