In [11]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.dpi'] = 70 #display 70 dpi in Jupyter Notebook, may consider100 dpi 
plt.rcParams['savefig.dpi'] = 300 #define 300 dpi for saving figures

import seaborn as sns
## here are some settings 
sns.set_style('whitegrid')
sns.set(rc={"figure.dpi":70, 'savefig.dpi':300}) #defining dpi setting
sns.set_context('notebook')
sns.set_style("ticks")
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('retina')
# Tells matplotlib to display images inline instead of a new window
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
random.seed(1000)

from time import time
import timeit #imports timeit module
start_time = timeit.default_timer() #defines start time so computational time can be calculated
print("Hello World")
elapsed = timeit.default_timer() - start_time #gives total computation time
print("---Run time is %s seconds ---" % elapsed) #prints computation time
print()

Hello World
---Run time is 0.0003752000002350542 seconds ---



In [12]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
from sklearn.preprocessing import PolynomialFeatures

import sklearn.linear_model as skl_lm
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn import neighbors
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.tree import DecisionTreeRegressor 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.tree import export_graphviz
from sklearn.svm import SVC

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import train_test_split

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import mean_squared_error

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier

In [18]:
df2017 = pd.read_csv('SRER_2017_training_bi.csv').dropna()
df2021 = pd.read_csv("SRER21_dataset_v1.csv").dropna()
df2017["Year"] = '2017'
df2021["Year"] = '2021'
frames = [df2017,df2021]
dfCombined = pd.concat(frames)
dfCombined = dfCombined.reindex(columns=['OID_','Id', 'gridcode','Shape_Length','Shape_Area', 'CH_mean', 'ARVI_max', 'ARVI_mean', 'ARVI_med', 'EVI_max', 'EVI_mean', 'EVI_med', 'NDVI_max', 'NDVI_mean', 'NDVI_med', 'SAVI_max', 'SAVI_mean', 'SAVI_med', 'Year', 'Veg_class'])



dfJornada = pd.read_csv("JORN17_dataset_v1.csv").dropna()
dfCombined

OID_    Id  gridcode  Shape_Length  Shape_Area   CH_mean  ARVI_max  \
0        1     2         2          41.6       17.41  0.190714  0.609099   
1        2     3         3          31.4        5.05  0.045000  0.387755   
2        3     5         5          33.4        4.84  0.010000  0.038844   
3        4     6         6          32.2       14.20  0.011667  0.189842   
4        5     7         7          28.8       10.73  0.013750  0.322694   
...    ...   ...       ...           ...         ...       ...       ...   
7758  7760  7760      7760          10.2        1.50  1.000000  0.584517   
7759  7761  7761      7761          12.0        1.59  0.666667  0.568966   
7760  7762  7762      7762          14.6        3.20  1.000000  0.483734   
7761  7763  7763      7763          10.6        2.24  0.500000  0.517261   
7765  7767  7767      7767          18.4        3.15  0.666667  0.704283   

      ARVI_mean  ARVI_med   EVI_max  EVI_mean   EVI_med  NDVI_max  NDVI_mean  \
0      0.344183  0.379428  0.443455  0.292047  0.290985  0.665698   0.476709   
1      0.245301  0.274936  0.332059  0.252919  0.244477  0.526375   0.406745   
2      0.004040  0.026805  0.150550  0.131985  0.134891  0.208300   0.181575   
3      0.033418  0.018961  0.198972  0.141579  0.138338  0.341480   0.207390   
4      0.080315  0.061453  0.248442  0.158710  0.142326  0.457103   0.247391   
...         ...       ...       ...       ...       ...       ...        ...   
7758   0.584517  0.584517  0.446516  0.446516  0.446516  0.653532   0.653532   
7759   0.536690  0.552596  0.403695  0.378935  0.397165  0.640278   0.615736   
7760   0.482610  0.482610  0.324235  0.322043  0.322043  0.577511   0.576554   
7761   0.446487  0.446487  0.412901  0.364414  0.364414  0.608110   0.559486   
7765   0.515684  0.423021  0.458583  0.326245  0.268593  0.739447   0.596799   

      NDVI_med  SAVI_max  SAVI_mean  SAVI_med  Year  Veg_class  
0     0.507514  0.406991   0.286203  0.288351  2017      woody  
1     0.433791  0.328585   0.254814  0.248126  2017  non-woody  
2     0.205117  0.150184   0.131642  0.135063  2017  non-woody  
3     0.197327  0.197330   0.141500  0.138725  2017  non-woody  
4     0.228112  0.248598   0.158618  0.142817  2017  non-woody  
...        ...       ...        ...       ...   ...        ...  
7758  0.708677  0.411416   0.411416  0.411416  2021      woody  
7759  0.653532  0.377543   0.358073  0.373771  2021      woody  
7760  0.627957  0.314608   0.312786  0.312786  2021      woody  
7761  0.576554  0.386289   0.348984  0.348984  2021      woody  
7765  0.620037  0.426432   0.314592  0.266999  2021      woody  

[10336 rows x 20 columns]

In [14]:
df2017.Veg_class = df2017.Veg_class.map({'non-woody':0, 'woody':1})
df2021.Veg_class = df2021.Veg_class.map({'non-woody':0, 'woody':1})
dfJornada.Veg_class = dfJornada.Veg_class.map({'non-woody':0, 'woody':1})


dfJornada.head(5)

OID_  Id  gridcode  Shape_Length  Shape_Area  CH_mean  ARVI_mean  ARVI_med  \
0     2   2         2          16.0        4.79   0.0100   0.223962  0.226896   
1     3   3         3           8.6        2.24   0.0100   0.287822  0.287822   
2     4   4         4          27.8       11.12   0.0125   0.289236  0.313074   
3     5   5         5          24.2       10.62   0.0600   0.330255  0.375986   
4     6   6         6          17.4        6.10   0.0120   0.275800  0.341526   

   ARVI_max  EVI_mean   EVI_med   EVI_max  NDVI_mean  NDVI_med  NDVI_max  \
0  0.239161  0.273236  0.274394  0.307885   0.402131  0.406066  0.427636   
1  0.316384  0.302193  0.302193  0.305906   0.448325  0.448325  0.469259   
2  0.459671  0.300200  0.318621  0.374641   0.447470  0.466219  0.570786   
3  0.498250  0.313174  0.335601  0.386369   0.477596  0.517136  0.598966   
4  0.416294  0.264112  0.280268  0.314841   0.431575  0.487791  0.518614   

   SAVI_mean  SAVI_med  SAVI_max  Veg_class  
0   0.278782  0.280285  0.316995          1  
1   0.301407  0.301407  0.304224          1  
2   0.298798  0.314429  0.358302          1  
3   0.309534  0.325886  0.368766          1  
4   0.266352  0.273629  0.312146          1

In [15]:
X = df2017.drop(["Veg_class"], axis=1)
y = df2021.Veg_class[0:4339]
print(X.shape)
print(y.shape)
print(X)

(4339, 19)
(4339,)
      OID_    Id  gridcode  Shape_Length  Shape_Area   CH_mean  ARVI_max  \
0        1     2         2          41.6       17.41  0.190714  0.609099   
1        2     3         3          31.4        5.05  0.045000  0.387755   
2        3     5         5          33.4        4.84  0.010000  0.038844   
3        4     6         6          32.2       14.20  0.011667  0.189842   
4        5     7         7          28.8       10.73  0.013750  0.322694   
...    ...   ...       ...           ...         ...       ...       ...   
4334  4335  4487      4487           8.8        2.30  0.020000  0.290182   
4335  4336  4488      4488          10.8        2.03  0.020000  0.408320   
4336  4337  4489      4489          11.8        2.62  0.015000  0.437195   
4337  4338  4490      4490          11.2        3.09  0.015000  0.570094   
4338  4339  4491      4491          14.8        3.33  0.865000  0.487398   

      ARVI_mean  ARVI_med   EVI_max  EVI_mean   EVI_med  NDVI_max  N

In [47]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6) #criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

---Run time is 7.317081600000051 seconds ---

Accuracy of each fold: 
 [0.7131336405529954, 0.6820276497695853, 0.6797235023041475, 0.7235023041474654, 0.6828143021914648]
Avg accuracy: 0.6962402797931316
Std of accuracy : 
0.01835027670105538

[[ 250 1209]
 [ 109 2771]]

              precision    recall  f1-score   support

           0       0.70      0.17      0.28      1459
           1       0.70      0.96      0.81      2880

    accuracy                           0.70      4339
   macro avg       0.70      0.57      0.54      4339
weighted avg       0.70      0.70      0.63      4339

0.17135023989033585
0.9621527777777777
0.6963788300835655
0.27502750275027504


In [48]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 35.17050530000006 seconds ---

Accuracy of each fold: 
 [0.7523041474654378, 0.7776497695852534, 0.7707373271889401, 0.7407834101382489, 0.7854671280276817]
Avg accuracy: 0.7653883564811123
Std of accuracy : 
0.016484603215509756

[[ 676  783]
 [ 235 2645]]

              precision    recall  f1-score   support

           0       0.74      0.46      0.57      1459
           1       0.77      0.92      0.84      2880

    accuracy                           0.77      4339
   macro avg       0.76      0.69      0.70      4339
weighted avg       0.76      0.77      0.75      4339

0.46333104866346814
0.9184027777777778
0.7420417124039517
0.5704641350210969


In [ ]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

In [ ]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

In [ ]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2017.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = df2017.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)



In [ ]:
#2021 SRER to 2017 SRER

In [ ]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6) #criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

In [ ]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print(sensitivity)
print(specificity)
print(precision)
print(f1_score)

#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

In [ ]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

In [56]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(df2017): 
    
    X_train = df2021.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = df2021.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 936.3371799000001 seconds ---

Accuracy of each fold: 
 [0.48502304147465436, 0.4827188940092166, 0.40898617511520735, 0.5080645161290323, 0.5155709342560554]
Avg accuracy: 0.4800727121968332
Std of accuracy : 
0.03775835973435534

[[ 514 1574]
 [ 682 1569]]

              precision    recall  f1-score   support

           0       0.43      0.25      0.31      2088
           1       0.50      0.70      0.58      2251

    accuracy                           0.48      4339
   macro avg       0.46      0.47      0.45      4339
weighted avg       0.47      0.48      0.45      4339

Sensitivity: 0.24616858237547892
Specificity: 0.6970235450910707
Precision: 0.4297658862876254
F1_Score: 0.31303288672350793


In [73]:
df2017 = pd.read_csv('SRER_2017_training_bi.csv').dropna()
dfJornada = pd.read_csv("JORN17_dataset_v1.csv")
dfJornada.head()

OID_  Id  gridcode  Shape_Length  Shape_Area  CH_mean  ARVI_mean  ARVI_med  \
0     2   2         2          16.0        4.79   0.0100   0.223962  0.226896   
1     3   3         3           8.6        2.24   0.0100   0.287822  0.287822   
2     4   4         4          27.8       11.12   0.0125   0.289236  0.313074   
3     5   5         5          24.2       10.62   0.0600   0.330255  0.375986   
4     6   6         6          17.4        6.10   0.0120   0.275800  0.341526   

   ARVI_max  EVI_mean   EVI_med   EVI_max  NDVI_mean  NDVI_med  NDVI_max  \
0  0.239161  0.273236  0.274394  0.307885   0.402131  0.406066  0.427636   
1  0.316384  0.302193  0.302193  0.305906   0.448325  0.448325  0.469259   
2  0.459671  0.300200  0.318621  0.374641   0.447470  0.466219  0.570786   
3  0.498250  0.313174  0.335601  0.386369   0.477596  0.517136  0.598966   
4  0.416294  0.264112  0.280268  0.314841   0.431575  0.487791  0.518614   

   SAVI_mean  SAVI_med  SAVI_max Veg_class  
0   0.278782  0.280285  0.316995     woody  
1   0.301407  0.301407  0.304224     woody  
2   0.298798  0.314429  0.358302     woody  
3   0.309534  0.325886  0.368766     woody  
4   0.266352  0.273629  0.312146     woody

In [74]:
#2017 JORN to 2017 SRER
df2017.Veg_class = df2017.Veg_class.map({'non-woody':0, 'woody':1})
df2021.Veg_class = df2021.Veg_class.map({'non-woody':0, 'woody':1})
dfJornada.Veg_class = dfJornada.Veg_class.map({'non-woody':0, 'woody':1})


df2017.head(5)

OID_  Id  gridcode  Shape_Length  Shape_Area   CH_mean  ARVI_max  \
0     1   2         2          41.6       17.41  0.190714  0.609099   
1     2   3         3          31.4        5.05  0.045000  0.387755   
2     3   5         5          33.4        4.84  0.010000  0.038844   
3     4   6         6          32.2       14.20  0.011667  0.189842   
4     5   7         7          28.8       10.73  0.013750  0.322694   

   ARVI_mean  ARVI_med   EVI_max  EVI_mean   EVI_med  NDVI_max  NDVI_mean  \
0   0.344183  0.379428  0.443455  0.292047  0.290985  0.665698   0.476709   
1   0.245301  0.274936  0.332059  0.252919  0.244477  0.526375   0.406745   
2   0.004040  0.026805  0.150550  0.131985  0.134891  0.208300   0.181575   
3   0.033418  0.018961  0.198972  0.141579  0.138338  0.341480   0.207390   
4   0.080315  0.061453  0.248442  0.158710  0.142326  0.457103   0.247391   

   NDVI_med  SAVI_max  SAVI_mean  SAVI_med  Veg_class  
0  0.507514  0.406991   0.286203  0.288351          1  
1  0.433791  0.328585   0.254814  0.248126          0  
2  0.205117  0.150184   0.131642  0.135063          0  
3  0.197327  0.197330   0.141500  0.138725          0  
4  0.228112  0.248598   0.158618  0.142817          0

In [88]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6) #criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 4073.0798219999997 seconds ---

Accuracy of each fold: 
 [0.5547169811320755, 0.5377358490566038, 0.439622641509434, 0.5188679245283019, 0.5066162570888468]
Avg accuracy: 0.5115119306630524
Std of accuracy : 
0.03949814791213834

[[660 693]
 [601 695]]

              precision    recall  f1-score   support

   non-woody       0.52      0.49      0.50      1353
       woody       0.50      0.54      0.52      1296

    accuracy                           0.51      2649
   macro avg       0.51      0.51      0.51      2649
weighted avg       0.51      0.51      0.51      2649

Sensitivity: 0.4878048780487805
Specificity: 0.5362654320987654
Precision: 0.5233941316415543
F1_Score: 0.504973221117062


In [85]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 3468.1333168 seconds ---

Accuracy of each fold: 
 [0.5037735849056604, 0.4320754716981132, 0.46037735849056605, 0.5150943396226415, 0.4782608695652174]
Avg accuracy: 0.4779163248564397
Std of accuracy : 
0.029866103025777527

[[504 849]
 [534 762]]

              precision    recall  f1-score   support

   non-woody       0.49      0.37      0.42      1353
       woody       0.47      0.59      0.52      1296

    accuracy                           0.48      2649
   macro avg       0.48      0.48      0.47      2649
weighted avg       0.48      0.48      0.47      2649

Sensitivity: 0.37250554323725055
Specificity: 0.5879629629629629
Precision: 0.48554913294797686
F1_Score: 0.4215809284818068


In [86]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 3680.0060697999998 seconds ---

Accuracy of each fold: 
 [0.530188679245283, 0.4528301886792453, 0.5113207547169811, 0.5528301886792453, 0.5444234404536862]
Avg accuracy: 0.5183186503548882
Std of accuracy : 
0.03564018261871245

[[ 260 1093]
 [ 183 1113]]

              precision    recall  f1-score   support

   non-woody       0.59      0.19      0.29      1353
       woody       0.50      0.86      0.64      1296

    accuracy                           0.52      2649
   macro avg       0.55      0.53      0.46      2649
weighted avg       0.55      0.52      0.46      2649

Sensitivity: 0.19216555801921656
Specificity: 0.8587962962962963
Precision: 0.5869074492099323
F1_Score: 0.289532293986637


In [87]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 3783.8739254 seconds ---

Accuracy of each fold: 
 [0.45660377358490567, 0.38301886792452833, 0.49433962264150944, 0.4679245283018868, 0.4914933837429111]
Avg accuracy: 0.45867603523914824
Std of accuracy : 
0.04040471677314628

[[514 839]
 [595 701]]

              precision    recall  f1-score   support

   non-woody       0.46      0.38      0.42      1353
       woody       0.46      0.54      0.49      1296

    accuracy                           0.46      2649
   macro avg       0.46      0.46      0.46      2649
weighted avg       0.46      0.46      0.46      2649

Sensitivity: 0.37989652623798964
Specificity: 0.5408950617283951
Precision: 0.46348061316501354
F1_Score: 0.4175467099918765


In [89]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6) #criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 4141.4645392 seconds ---

Accuracy of each fold: 
 [0.6584905660377358, 0.7037735849056603, 0.5962264150943396, 0.6528301886792452, 0.6748582230623819]
Avg accuracy: 0.6572357955558725
Std of accuracy : 
0.03526880807172541

[[ 242  678]
 [ 230 1499]]

              precision    recall  f1-score   support

   non-woody       0.51      0.26      0.35       920
       woody       0.69      0.87      0.77      1729

    accuracy                           0.66      2649
   macro avg       0.60      0.57      0.56      2649
weighted avg       0.63      0.66      0.62      2649

Sensitivity: 0.26304347826086955
Specificity: 0.8669751301330249
Precision: 0.5127118644067796
F1_Score: 0.3477011494252874


In [90]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2017.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2017.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 4437.916397 seconds ---

Accuracy of each fold: 
 [0.5037735849056604, 0.4320754716981132, 0.46037735849056605, 0.5150943396226415, 0.4782608695652174]
Avg accuracy: 0.4779163248564397
Std of accuracy : 
0.029866103025777527

[[504 849]
 [534 762]]

              precision    recall  f1-score   support

   non-woody       0.49      0.37      0.42      1353
       woody       0.47      0.59      0.52      1296

    accuracy                           0.48      2649
   macro avg       0.48      0.48      0.47      2649
weighted avg       0.48      0.48      0.47      2649

Sensitivity: 0.37250554323725055
Specificity: 0.5879629629629629
Precision: 0.48554913294797686
F1_Score: 0.4215809284818068


In [91]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 4618.5447133 seconds ---

Accuracy of each fold: 
 [0.6641509433962264, 0.6660377358490566, 0.6226415094339622, 0.6773584905660377, 0.6597353497164461]
Avg accuracy: 0.6579848057923458
Std of accuracy : 
0.018603352378887952

[[  30  890]
 [  16 1713]]

              precision    recall  f1-score   support

   non-woody       0.65      0.03      0.06       920
       woody       0.66      0.99      0.79      1729

    accuracy                           0.66      2649
   macro avg       0.66      0.51      0.43      2649
weighted avg       0.66      0.66      0.54      2649

Sensitivity: 0.03260869565217391
Specificity: 0.9907460960092539
Precision: 0.6521739130434783
F1_Score: 0.06211180124223602


In [92]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfJornada): 
    
    X_train = dfJornada.iloc[train_index, 5:18]
    X_test = df2021.iloc[test_index, 5:18]
    Y_train = dfJornada.iloc[train_index, -1]
    Y_test = df2021.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 4803.4391613 seconds ---

Accuracy of each fold: 
 [0.7075471698113207, 0.7056603773584905, 0.6641509433962264, 0.7188679245283018, 0.665406427221172]
Avg accuracy: 0.6923265684631023
Std of accuracy : 
0.02294541609661706

[[ 248  672]
 [ 143 1586]]

              precision    recall  f1-score   support

   non-woody       0.63      0.27      0.38       920
       woody       0.70      0.92      0.80      1729

    accuracy                           0.69      2649
   macro avg       0.67      0.59      0.59      2649
weighted avg       0.68      0.69      0.65      2649

Sensitivity: 0.26956521739130435
Specificity: 0.9172932330827067
Precision: 0.6342710997442456
F1_Score: 0.37833714721586575


In [79]:
#Combined Data

In [21]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = DecisionTreeClassifier(max_depth=6)
kf = KFold(n_splits=5, random_state=1, shuffle=True)
#criterion='entropy'
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))

acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:19]
    X_test = dfCombined.iloc[test_index, 5:19]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)
print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

---Run time is 630.8209587000001 seconds ---

Accuracy of each fold: 
 [0.7504835589941973, 0.7629414610546686, 0.7518142235123367, 0.7716497339138848, 0.7634252539912917]
Avg accuracy: 0.7600628462932758
Std of accuracy : 
0.007920236058923013

[[2898 1158]
 [1322 4958]]

              precision    recall  f1-score   support

   non-woody       0.69      0.71      0.70      4056
       woody       0.81      0.79      0.80      6280

    accuracy                           0.76     10336
   macro avg       0.75      0.75      0.75     10336
weighted avg       0.76      0.76      0.76     10336

Sensitivity: 0.7144970414201184
Specificity: 0.7894904458598726
Precision: 0.6867298578199053
F1_Score: 0.7003383276945385


In [22]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
kf = KFold(n_splits=5, random_state=3, shuffle=True)
model = RandomForestClassifier(max_features = 10, random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:19]
    X_test = dfCombined.iloc[test_index, 5:19]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1136.2195672000003 seconds ---

Accuracy of each fold: 
 [0.7717601547388782, 0.7851959361393324, 0.7735849056603774, 0.7813255926463474, 0.7561683599419449]
Avg accuracy: 0.773606989825376
Std of accuracy : 
0.010013966306454505

[[2922 1134]
 [1206 5074]]

              precision    recall  f1-score   support

   non-woody       0.71      0.72      0.71      4056
       woody       0.82      0.81      0.81      6280

    accuracy                           0.77     10336
   macro avg       0.76      0.76      0.76     10336
weighted avg       0.77      0.77      0.77     10336

Sensitivity: 0.7204142011834319
Specificity: 0.8079617834394904
Precision: 0.7078488372093024
F1_Score: 0.7140762463343109


In [23]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model = AdaBoostClassifier(n_estimators=500, learning_rate = 0.1, algorithm="SAMME.R", random_state=2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:18]
    X_test = dfCombined.iloc[test_index, 5:18]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1371.3155979000003 seconds ---

Accuracy of each fold: 
 [0.769825918762089, 0.7880986937590712, 0.7822931785195936, 0.7687469762941461, 0.772133526850508]
Avg accuracy: 0.7762196588370815
Std of accuracy : 
0.007634349784460595

[[3026 1030]
 [1283 4997]]

              precision    recall  f1-score   support

   non-woody       0.70      0.75      0.72      4056
       woody       0.83      0.80      0.81      6280

    accuracy                           0.78     10336
   macro avg       0.77      0.77      0.77     10336
weighted avg       0.78      0.78      0.78     10336

Sensitivity: 0.7460552268244576
Specificity: 0.7957006369426751
Precision: 0.7022511023439313
F1_Score: 0.7234907352062164


In [24]:
crossvalidation = KFold(n_splits=5, random_state=2, shuffle=True)
model =  GradientBoostingClassifier(n_estimators = 500, 
                                           learning_rate = 0.1, 
                                           max_depth = 4, 
                                           random_state = 2)
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#scores = cross_val_score(model, X, y, cv=crossvalidation)
#print('Accuracy of each fold: \n {}'.format(scores))
#print()
#print("Avg accuracy: {}".format(scores.mean()))
#print(model)


acc_score = [];
Truth = [];
Output = [];

for train_index, test_index in kf.split(dfCombined): 
    
    X_train = dfCombined.iloc[train_index, 5:18]
    X_test = dfCombined.iloc[test_index, 5:18]
    Y_train = dfCombined.iloc[train_index, -1]
    Y_test = dfCombined.iloc[test_index, -1]

    model.fit(X_train, Y_train)
    pred_values = model.predict(X_test)

    acc = accuracy_score(Y_test, pred_values)
    acc_score.append(acc)

    Truth.extend(Y_test.values.reshape(Y_test.shape[0])) 
    Output.extend(pred_values)

elapsed = timeit.default_timer() - start_time



print("---Run time is %s seconds ---" % elapsed)
print()
print('Accuracy of each fold: \n {}'.format(acc_score))
print("Avg accuracy: {}".format(np.mean(acc_score)))
print('Std of accuracy : \n{}'.format(np.std(acc_score)))
print()
print(confusion_matrix(Truth, Output))
print()
print(classification_report(Truth, Output))

cm = confusion_matrix(Truth, Output)

sensitivity = cm[0][0]/(cm[0][0]+cm[0][1])
specificity = cm[1][1]/(cm[1][0]+cm[1][1])
precision = (cm[0][0])/(cm[0][0]+cm[1][0])
f1_score = (2*precision*sensitivity)/(precision+sensitivity)

print("Sensitivity: {}".format(sensitivity))
print("Specificity: {}".format(specificity))
print("Precision: {}".format(precision))
print("F1_Score: {}".format(f1_score))

      
#statallfeatures_dic['Run Time'].append(elapsed)
#statallfeatures_dic['Accuracy'].append(np.mean(acc_score))
#statallfeatures_dic['Standard Error'].append(np.std(acc_score))
#statallfeatures_dic['Sensitivity'].append(sensitivity)
#statallfeatures_dic['Specificity'].append(specificity)
#statallfeatures_dic['Precision'].append(precision)
#statallfeatures_dic['F1_Score'].append(f1_score)

#indaccs_dic['LogReg']=acc_score

---Run time is 1634.7188446000005 seconds ---

Accuracy of each fold: 
 [0.7678916827852998, 0.7866473149492017, 0.768263183357523, 0.7803580067731011, 0.7668118045476536]
Avg accuracy: 0.7739943984825559
Std of accuracy : 
0.008028342629858897

[[2895 1161]
 [1175 5105]]

              precision    recall  f1-score   support

   non-woody       0.71      0.71      0.71      4056
       woody       0.81      0.81      0.81      6280

    accuracy                           0.77     10336
   macro avg       0.76      0.76      0.76     10336
weighted avg       0.77      0.77      0.77     10336

Sensitivity: 0.7137573964497042
Specificity: 0.8128980891719745
Precision: 0.7113022113022113
F1_Score: 0.7125276888998276
